//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Assets/PlayerTestInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/PlayerTestInput.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PlayerTestInput: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PlayerTestInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""PlayerTestInput"",
    ""maps"": [
        {
            ""name"": ""TestInput"",
            ""id"": ""828e895c-db0f-439e-90c9-cd8b49f27e18"",
            ""actions"": [
                {
                    ""name"": ""ChangePositionX"",
                    ""type"": ""Button"",
                    ""id"": ""35219f43-3024-4847-b15d-835117ac8c89"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangePositionY"",
                    ""type"": ""Button"",
                    ""id"": ""4f1e9eb2-f14c-4f9c-82a3-f869aa671d2c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""446bc992-fd44-48ca-ada6-a7e031a024d5"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangePositionX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7149bc6f-ccf5-4ad0-97f9-e0086d23c92a"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangePositionY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // TestInput
        m_TestInput = asset.FindActionMap("TestInput", throwIfNotFound: true);
        m_TestInput_ChangePositionX = m_TestInput.FindAction("ChangePositionX", throwIfNotFound: true);
        m_TestInput_ChangePositionY = m_TestInput.FindAction("ChangePositionY", throwIfNotFound: true);
    }

    ~@PlayerTestInput()
    {
        UnityEngine.Debug.Assert(!m_TestInput.enabled, "This will cause a leak and performance issues, PlayerTestInput.TestInput.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // TestInput
    private readonly InputActionMap m_TestInput;
    private List<ITestInputActions> m_TestInputActionsCallbackInterfaces = new List<ITestInputActions>();
    private readonly InputAction m_TestInput_ChangePositionX;
    private readonly InputAction m_TestInput_ChangePositionY;
    /// <summary>
    /// Provides access to input actions defined in input action map "TestInput".
    /// </summary>
    public struct TestInputActions
    {
        private @PlayerTestInput m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public TestInputActions(@PlayerTestInput wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "TestInput/ChangePositionX".
        /// </summary>
        public InputAction @ChangePositionX => m_Wrapper.m_TestInput_ChangePositionX;
        /// <summary>
        /// Provides access to the underlying input action "TestInput/ChangePositionY".
        /// </summary>
        public InputAction @ChangePositionY => m_Wrapper.m_TestInput_ChangePositionY;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_TestInput; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="TestInputActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(TestInputActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="TestInputActions" />
        public void AddCallbacks(ITestInputActions instance)
        {
            if (instance == null || m_Wrapper.m_TestInputActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TestInputActionsCallbackInterfaces.Add(instance);
            @ChangePositionX.started += instance.OnChangePositionX;
            @ChangePositionX.performed += instance.OnChangePositionX;
            @ChangePositionX.canceled += instance.OnChangePositionX;
            @ChangePositionY.started += instance.OnChangePositionY;
            @ChangePositionY.performed += instance.OnChangePositionY;
            @ChangePositionY.canceled += instance.OnChangePositionY;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="TestInputActions" />
        private void UnregisterCallbacks(ITestInputActions instance)
        {
            @ChangePositionX.started -= instance.OnChangePositionX;
            @ChangePositionX.performed -= instance.OnChangePositionX;
            @ChangePositionX.canceled -= instance.OnChangePositionX;
            @ChangePositionY.started -= instance.OnChangePositionY;
            @ChangePositionY.performed -= instance.OnChangePositionY;
            @ChangePositionY.canceled -= instance.OnChangePositionY;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="TestInputActions.UnregisterCallbacks(ITestInputActions)" />.
        /// </summary>
        /// <seealso cref="TestInputActions.UnregisterCallbacks(ITestInputActions)" />
        public void RemoveCallbacks(ITestInputActions instance)
        {
            if (m_Wrapper.m_TestInputActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="TestInputActions.AddCallbacks(ITestInputActions)" />
        /// <seealso cref="TestInputActions.RemoveCallbacks(ITestInputActions)" />
        /// <seealso cref="TestInputActions.UnregisterCallbacks(ITestInputActions)" />
        public void SetCallbacks(ITestInputActions instance)
        {
            foreach (var item in m_Wrapper.m_TestInputActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TestInputActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="TestInputActions" /> instance referencing this action map.
    /// </summary>
    public TestInputActions @TestInput => new TestInputActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "TestInput" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="TestInputActions.AddCallbacks(ITestInputActions)" />
    /// <seealso cref="TestInputActions.RemoveCallbacks(ITestInputActions)" />
    public interface ITestInputActions
    {
        /// <summary>
        /// Method invoked when associated input action "ChangePositionX" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnChangePositionX(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ChangePositionY" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnChangePositionY(InputAction.CallbackContext context);
    }
}
